#!/bin/sh
#
# pick buffers
#
# requires:
# - fzf (https://github.com/junegunn/fzf)
# - highlight (faster than bat) (https://gitlab.com/saalen/highlight)

kks get %val[buflist] |
	grep -F "$*" |
	fzf --height 100% --prompt 'buf> ' --preview 'kks cat -b {} | highlight --line-range=1-100 --force -O ansi' |
	while read -r name; do
		kks send buffer "$name"
	done
