#!/bin/sh
# select kak session and client for setting environment
# use as `eval (kak-select)`

command kak -clear

kks list |
	column --table |
	fzf --preview="KKS_SESSION={1} KKS_CLIENT={2} kks cat" |
	awk '{print "export KKS_SESSION=" $1 "; export KKS_CLIENT=" $2}'
