#!/bin/sh
#
# select kak session and client to set environment
# use as `eval (kak-select)`, eg: `alias ks="eval (kak-select)"` in shell config
#
# requires:
# - fzf (https://github.com/junegunn/fzf)

command kak -clear

kks list |
	column --table |
	fzf --preview="KKS_SESSION={1} KKS_CLIENT={2} kks cat" |
	awk '{print "export KKS_SESSION=" $1 "; export KKS_CLIENT=" $2}'
